//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CoatiSoftware.SourcetrailDB {

public enum ReferenceKind {
  REFERENCE_TYPE_USAGE,
  REFERENCE_USAGE,
  REFERENCE_CALL,
  REFERENCE_INHERITANCE,
  REFERENCE_OVERRIDE,
  REFERENCE_TYPE_ARGUMENT,
  REFERENCE_TEMPLATE_SPECIALIZATION,
  REFERENCE_INCLUDE,
  REFERENCE_IMPORT,
  REFERENCE_MACRO_USAGE,
  REFERENCE_ANNOTATION_USAGE
}

}
