//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CoatiSoftware.SourcetrailDB {

class sourcetraildbPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="SWIGRegisterExceptionCallbacks_sourcetraildb")]
    public static extern void SWIGRegisterExceptionCallbacks_sourcetraildb(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_sourcetraildb")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_sourcetraildb(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_sourcetraildb(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_sourcetraildb(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="SWIGRegisterStringCallback_sourcetraildb")]
    public static extern void SWIGRegisterStringCallback_sourcetraildb(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_sourcetraildb(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static sourcetraildbPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_getVersionString___")]
  public static extern string getVersionString();

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_getSupportedDatabaseVersion___")]
  public static extern int getSupportedDatabaseVersion();

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_getLastError___")]
  public static extern string getLastError();

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_clearLastError___")]
  public static extern void clearLastError();

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_open___")]
  public static extern bool open(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_close___")]
  public static extern bool close();

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_clear___")]
  public static extern bool clear();

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_isEmpty___")]
  public static extern bool isEmpty();

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_isCompatible___")]
  public static extern bool isCompatible();

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_getLoadedDatabaseVersion___")]
  public static extern int getLoadedDatabaseVersion();

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_beginTransaction___")]
  public static extern bool beginTransaction();

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_commitTransaction___")]
  public static extern bool commitTransaction();

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_rollbackTransaction___")]
  public static extern bool rollbackTransaction();

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_optimizeDatabaseMemory___")]
  public static extern bool optimizeDatabaseMemory();

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordSymbol___")]
  public static extern int recordSymbol(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordSymbolDefinitionKind___")]
  public static extern bool recordSymbolDefinitionKind(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordSymbolKind___")]
  public static extern bool recordSymbolKind(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordSymbolLocation___")]
  public static extern bool recordSymbolLocation(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordSymbolScopeLocation___")]
  public static extern bool recordSymbolScopeLocation(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordSymbolSignatureLocation___")]
  public static extern bool recordSymbolSignatureLocation(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordReference___")]
  public static extern int recordReference(int jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordReferenceLocation___")]
  public static extern bool recordReferenceLocation(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordReferenceIsAmbiguous___")]
  public static extern bool recordReferenceIsAmbiguous(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordReferenceToUnsolvedSymhol___")]
  public static extern int recordReferenceToUnsolvedSymhol(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordQualifierLocation___")]
  public static extern bool recordQualifierLocation(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordFile___")]
  public static extern int recordFile(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordFileLanguage___")]
  public static extern bool recordFileLanguage(int jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordLocalSymbol___")]
  public static extern int recordLocalSymbol(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordLocalSymbolLocation___")]
  public static extern bool recordLocalSymbolLocation(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordAtomicSourceRange___")]
  public static extern bool recordAtomicSourceRange(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("SourcetrailDB", EntryPoint="CSharp_CoatiSoftwarefSourcetrailDB_recordError___")]
  public static extern bool recordError(string jarg1, bool jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7);
}

}
