//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CoatiSoftware.SourcetrailDB {

public enum SymbolKind {
  SYMBOL_TYPE,
  SYMBOL_BUILTIN_TYPE,
  SYMBOL_MODULE,
  SYMBOL_NAMESPACE,
  SYMBOL_PACKAGE,
  SYMBOL_STRUCT,
  SYMBOL_CLASS,
  SYMBOL_INTERFACE,
  SYMBOL_ANNOTATION,
  SYMBOL_GLOBAL_VARIABLE,
  SYMBOL_FIELD,
  SYMBOL_FUNCTION,
  SYMBOL_METHOD,
  SYMBOL_ENUM,
  SYMBOL_ENUM_CONSTANT,
  SYMBOL_TYPEDEF,
  SYMBOL_TYPE_PARAMETER,
  SYMBOL_MACRO,
  SYMBOL_UNION
}

}
